spring.application.name=SchoolWebsite

spring.datasource.url=jdbc:mysql://localhost:3306/school_dbms?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SQLin2026

# Session settings
server.servlet.session.timeout=2h
server.servlet.session.cookie.max-age=2h
